"""empty message

Revision ID: 6afa93d9444c
Revises: 
Create Date: 2022-03-27 22:32:01.198086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6afa93d9444c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('lastlogin', sa.TIMESTAMP(), nullable=True),
    sa.Column('signature', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_vaiants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pass_part', sa.String(), nullable=True),
    sa.Column('human_readable', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variants',
    sa.Column('login_id', sa.Integer(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('revision', sa.String(), nullable=True),
    sa.Column('letters', sa.Boolean(), nullable=True),
    sa.Column('digits', sa.Boolean(), nullable=True),
    sa.Column('symbols', sa.Boolean(), nullable=True),
    sa.Column('underscore', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('login_id', 'resource')
    )
    op.drop_index('login', table_name='login')
    op.drop_table('login')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('login', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('lastlogin', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('signature', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('lastresource', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_on', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index('login', 'login', ['login'], unique=False)
    op.drop_table('variants')
    op.drop_table('resource_vaiants')
    op.drop_table('logins')
    # ### end Alembic commands ###
